version: "3"
services:
  app:
    restart: always
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:80"
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=urmartshop
